# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Mines' do

pod 'j2objc-model-debug', :configuration => ['Debug'], :path => '/Users/leck/projects/devisnik/mines/model/build'
pod 'j2objc-model-release', :configuration => ['Release'], :path => '/Users/leck/projects/devisnik/mines/model/build'
end

target 'MinesTests' do

pod 'j2objc-model-debug', :configuration => ['Debug'], :path => '/Users/leck/projects/devisnik/mines/model/build'
pod 'j2objc-model-release', :configuration => ['Release'], :path => '/Users/leck/projects/devisnik/mines/model/build'
end
